spring.application.name=file-service
server.port=8082

# Local
app.dict.words.file-path=D:/file-service/file-service/my-words.txt
app.dict.phrases.file-path=D:/file-service/file-service/my-phrases.txt